version: "3"

services:
    router:
        build: ./router
        depends_on:
          backend:
            condition: service_healthy
        ports:
          - 80:80
        command:
          - /=http://backend:8001/

    backend:
        build: ./backend
        ports:
          - 8001:8001
        healthcheck:
          test: ["CMD", "curl", "-f", "http://localhost:8001"]
          interval: 15s
          timeout: 10s
          retries: 3
